name: tips
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1 # Added shared_preferences package


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Add assets for images
  assets:
    - image/bghome.png
    - image/logbg.png
    - image/bgnote.png
    - image/place1.jpg
    - image/place2.jpg
    - image/place3.jpg
    - image/place4.jpg
    - image/place5.jpg
    - image/bghomepage.png
    - image/bgbudget1.png